# Makefile generated by the project manager
#


# GENERATED: Mon Apr 14 17:38:29 +0900 2025
# DO NOT EDIT - file is regenerated whenever the project changes


## core information

ifeq ($(wildcard Makefile.mk),)
PRJ_DIR        = ..
else
PRJ_DIR        = .
endif
PRJ_FILE       = 1234.wpj
PRJ_FULL_PATH  = D:/vxworkspace/FMSH/1234
PRJ_TYPE       = vxWorks
PRJ_OBJS       = sysALib.o sysLib.o usrAppInit.o usrRtpAppInit.o prjConfig.o linkSyms.o
PRJ_MAKEFILE   = $(PRJ_DIR)/Makefile.mk
BOOT_OBJS      =  $(BOOT_EXTRA)
BUILD_SPEC     = default
BSP_DIR        = $(TGT_DIR)/config/fmsh_fmql_xj
VSB_DIR        = $(TGT_DIR)/lib
TGT_DIR        = $(WIND_BASE)/target



## set searching directories for dependencies

vpath %.c $(BSP_DIR)
vpath %.cpp $(BSP_DIR)
vpath %.cxx $(BSP_DIR)
vpath %.s $(BSP_DIR)


## build-configuration info

CPU            = ARMARCH7
TOOL           = gnu
TOOL_FAMILY    = gnu
ifeq ($(BUILD_SPEC),default)
DEFAULT_RULE   = vxWorks
endif

ifeq ($(BUILD_SPEC),default_rom)
DEFAULT_RULE   = vxWorks_rom
endif

ifeq ($(BUILD_SPEC),default_romCompress)
DEFAULT_RULE   = vxWorks_romCompress
endif

ifeq ($(BUILD_SPEC),default_romResident)
DEFAULT_RULE   = vxWorks_romResident
endif


## Memory adresses variables

RAM_LOW_ADRS = 200000
RAM_HIGH_ADRS = 1000000
LOCAL_MEM_LOCAL_ADRS = 00100000
DATA_SEG_ALIGN = 1
LOCAL_UNMAPPED_BASE_ADRS = 82000000
LOCAL_MEM_PHYS_ADRS = 20000000

## component-configuration info

COMPONENTS = DRV_ARM_GIC \
	DRV_MMCSTORAGE_CARD \
	DRV_SDSTORAGE_CARD \
	DRV_SIO_NS16550 \
	INCLUDE_ALT_SOC_GEN5_DW_END \
	INCLUDE_ALT_SOC_GEN5_TIMER \
	INCLUDE_ANSI_ABORT \
	INCLUDE_ANSI_ABS \
	INCLUDE_ANSI_ASSERT \
	INCLUDE_ANSI_ATOF \
	INCLUDE_ANSI_BSEARCH \
	INCLUDE_ANSI_CTYPE \
	INCLUDE_ANSI_LOCALE \
	INCLUDE_ANSI_LONGJMP \
	INCLUDE_ANSI_MATH \
	INCLUDE_ANSI_MEMCHR \
	INCLUDE_ANSI_MEMCMP \
	INCLUDE_ANSI_MEMCPY \
	INCLUDE_ANSI_MEMMOVE \
	INCLUDE_ANSI_MEMSET \
	INCLUDE_ANSI_STDIO \
	INCLUDE_ANSI_STDIO_EXTRA \
	INCLUDE_ANSI_STDLIB \
	INCLUDE_ANSI_STDLIB_NUMBERS \
	INCLUDE_ANSI_STRCASECMP \
	INCLUDE_ANSI_STRCAT \
	INCLUDE_ANSI_STRCMP \
	INCLUDE_ANSI_STRCPY \
	INCLUDE_ANSI_STRDUP \
	INCLUDE_ANSI_STRERROR \
	INCLUDE_ANSI_STRING \
	INCLUDE_ANSI_STRLCPY \
	INCLUDE_ANSI_STRLEN \
	INCLUDE_ANSI_STRNCASECMP \
	INCLUDE_ANSI_STRNCAT \
	INCLUDE_ANSI_STRNCMP \
	INCLUDE_ANSI_STRNCPY \
	INCLUDE_ANSI_STRTOD \
	INCLUDE_ANSI_TIME \
	INCLUDE_APPL_LOG_UTIL \
	INCLUDE_ARM_INTRINSIC_VFP_MATH \
	INCLUDE_ATOMIC_OPERATORS \
	INCLUDE_AVL_TREES \
	INCLUDE_AVL_UINT_TREES \
	INCLUDE_BASE_KERNEL \
	INCLUDE_BLIB \
	INCLUDE_BLIB_ARCH \
	INCLUDE_BOOT_HW_INIT \
	INCLUDE_BOOT_LINE_INIT \
	INCLUDE_BSP_MACROS \
	INCLUDE_CACHE_ENABLE \
	INCLUDE_CACHE_SUPPORT \
	INCLUDE_CLASS_LIB \
	INCLUDE_CLASS_LIST \
	INCLUDE_COMMON_NET \
	INCLUDE_COPROCESSOR \
	INCLUDE_COPROCESSOR_SHOW \
	INCLUDE_CTORS_DTORS \
	INCLUDE_DEBUG \
	INCLUDE_DEBUG_SHELL_CMD \
	INCLUDE_DEVICE_MANAGER \
	INCLUDE_DISK_UTIL \
	INCLUDE_DISK_UTIL_SHELL_CMD \
	INCLUDE_DLL \
	INCLUDE_DLL_ARCH \
	INCLUDE_DMA_SYS \
	INCLUDE_DOSFS \
	INCLUDE_DOSFS_CACHE \
	INCLUDE_DOSFS_CHKDSK \
	INCLUDE_DOSFS_DIR_FIXED \
	INCLUDE_DOSFS_DIR_VFAT \
	INCLUDE_DOSFS_FAT \
	INCLUDE_DOSFS_FMT \
	INCLUDE_DOSFS_MAIN \
	INCLUDE_DOSFS_PRTMSG_LEVEL \
	INCLUDE_DOSFS_SHOW \
	INCLUDE_DOSFS_VOL_BIO_BUFFER_SIZE \
	INCLUDE_EDR_POLICY_HOOKS \
	INCLUDE_EDR_STUB \
	INCLUDE_EDR_SYSDBG_FLAG \
	INCLUDE_END \
	INCLUDE_END_COMMON \
	INCLUDE_END_ETHER_HDR \
	INCLUDE_ENV_VARS \
	INCLUDE_ERF \
	INCLUDE_ETHERNET \
	INCLUDE_EVENTPOINT_STUB \
	INCLUDE_EXC_HANDLING \
	INCLUDE_EXC_SHOW \
	INCLUDE_EXC_TASK \
	INCLUDE_FLOATING_POINT \
	INCLUDE_FMSH_FMQL_GPIO \
	INCLUDE_FORMATTED_IO \
	INCLUDE_FORMATTED_OUT_BASIC \
	INCLUDE_FP_TYPE \
	INCLUDE_FS_EVENT_UTIL \
	INCLUDE_FS_MONITOR \
	INCLUDE_FTP \
	INCLUDE_GENERICPHY \
	INCLUDE_GETOPT \
	INCLUDE_GNU_INTRINSICS \
	INCLUDE_HANDLE_SHOW \
	INCLUDE_HASH \
	INCLUDE_HOOKS \
	INCLUDE_HOOK_SHOW \
	INCLUDE_HOST_TBL \
	INCLUDE_HWMEM_ALLOC \
	INCLUDE_HW_FP_MREGS \
	INCLUDE_HW_FP_SHOW \
	INCLUDE_IEEE_STATUS \
	INCLUDE_IFCONFIG \
	INCLUDE_INTCTLR_LIB \
	INCLUDE_IO_BASIC \
	INCLUDE_IO_FILE_SYSTEM \
	INCLUDE_IO_MISC \
	INCLUDE_IO_POSIX \
	INCLUDE_IO_REMOVABLE \
	INCLUDE_IO_RTP \
	INCLUDE_IO_SYSTEM \
	INCLUDE_IPAIP \
	INCLUDE_IPAIP_GLOBAL_CONFIGS \
	INCLUDE_IPATTACH \
	INCLUDE_IPCOM \
	INCLUDE_IPCOM_SHELL_CMD \
	INCLUDE_IPCOM_USE_AUTH \
	INCLUDE_IPCOM_USE_ETHERNET \
	INCLUDE_IPCOM_USE_INET \
	INCLUDE_IPCOM_USR \
	INCLUDE_IPNET \
	INCLUDE_IPNET_IFCONFIG_1 \
	INCLUDE_IPNET_LOOPBACK_CONFIG \
	INCLUDE_IPNET_SOCKET \
	INCLUDE_IPNET_STACK \
	INCLUDE_IPNET_USE_LOOPBACK \
	INCLUDE_IPNET_USE_ROUTESOCK \
	INCLUDE_IPNET_USE_SOCK_COMPAT \
	INCLUDE_IPPING_CMD \
	INCLUDE_IPPROXYARP \
	INCLUDE_IPTCP \
	INCLUDE_IPTELNETS \
	INCLUDE_IPV4 \
	INCLUDE_IPWRAP_GETIFADDRS \
	INCLUDE_IPWRAP_IFCONFIG \
	INCLUDE_IPWRAP_INETLIB \
	INCLUDE_IPWRAP_IPPROTO \
	INCLUDE_IPWRAP_PING \
	INCLUDE_ISR_DEFER \
	INCLUDE_JOB_DEFER \
	INCLUDE_JOB_QUEUE \
	INCLUDE_JOB_TASK \
	INCLUDE_KERNEL \
	INCLUDE_KERNEL_ARCH \
	INCLUDE_LINKBUFPOOL \
	INCLUDE_LOADER \
	INCLUDE_LOADER_CODE \
	INCLUDE_LOADER_HOOKS \
	INCLUDE_LOGGING \
	INCLUDE_LSTLIB \
	INCLUDE_MBUF_UTIL1 \
	INCLUDE_MEMORY_CONFIG \
	INCLUDE_MEM_MGR_BASIC \
	INCLUDE_MEM_MGR_FULL \
	INCLUDE_MEM_MGR_INFO \
	INCLUDE_MEM_SHOW \
	INCLUDE_MII_BUS \
	INCLUDE_MMU_BASIC \
	INCLUDE_MMU_GLOBAL_MAP \
	INCLUDE_MODULE_MANAGER \
	INCLUDE_MODULE_SHELL_CMD \
	INCLUDE_MSG_Q \
	INCLUDE_MSG_Q_CREATE_DELETE \
	INCLUDE_MSG_Q_EVENTS \
	INCLUDE_MSG_Q_INFO \
	INCLUDE_MUX \
	INCLUDE_MUX2 \
	INCLUDE_MUX2_OVER_END \
	INCLUDE_MUXTK \
	INCLUDE_MUXTK_OVER_END \
	INCLUDE_MUX_COMMON \
	INCLUDE_NETBUFLIB \
	INCLUDE_NETBUFPOOL \
	INCLUDE_NETMASK_GET \
	INCLUDE_NETWORK \
	INCLUDE_NET_BOOT \
	INCLUDE_NET_DAEMON \
	INCLUDE_NET_DRV \
	INCLUDE_NET_HOST_SETUP \
	INCLUDE_NET_REM_IO \
	INCLUDE_OBJ_INFO \
	INCLUDE_OBJ_LIB \
	INCLUDE_OBJ_LIB_ARCH \
	INCLUDE_OFFSET_SYMBOLS \
	INCLUDE_PARAM_SYS \
	INCLUDE_PING \
	INCLUDE_PIPES \
	INCLUDE_PLB_BUS \
	INCLUDE_POOL \
	INCLUDE_POSIX_CLOCKS \
	INCLUDE_POSIX_DIRLIB \
	INCLUDE_POSIX_FS \
	INCLUDE_POSIX_TIMERS \
	INCLUDE_PTYDRV \
	INCLUDE_Q_FIFO \
	INCLUDE_Q_PRI_BMAP \
	INCLUDE_Q_PRI_DELTA \
	INCLUDE_Q_PRI_LIST \
	INCLUDE_RAWFS \
	INCLUDE_REBOOT_HOOKS \
	INCLUDE_REMLIB \
	INCLUDE_RNG_BUF \
	INCLUDE_SD_BUS \
	INCLUDE_SELECT \
	INCLUDE_SELECT_SUPPORT \
	INCLUDE_SEM_BINARY \
	INCLUDE_SEM_BINARY_CREATE \
	INCLUDE_SEM_COUNTING \
	INCLUDE_SEM_COUNTING_CREATE \
	INCLUDE_SEM_DELETE \
	INCLUDE_SEM_EVENTS \
	INCLUDE_SEM_INFO \
	INCLUDE_SEM_LIB \
	INCLUDE_SEM_MUTEX \
	INCLUDE_SEM_MUTEX_CREATE \
	INCLUDE_SEM_READ_WRITE \
	INCLUDE_SEM_READ_WRITE_CREATE \
	INCLUDE_SEM_SHOW \
	INCLUDE_SHELL \
	INCLUDE_SHELL_BANNER \
	INCLUDE_SHELL_CORE \
	INCLUDE_SHELL_INTERP_C \
	INCLUDE_SHELL_INTERP_CMD \
	INCLUDE_SHELL_VI_MODE \
	INCLUDE_SIGEVENT \
	INCLUDE_SIGNALS \
	INCLUDE_SIGNAL_ARCH \
	INCLUDE_SIO \
	INCLUDE_SIO_UTILS \
	INCLUDE_SLL \
	INCLUDE_SOCKLIB \
	INCLUDE_SPINLOCK \
	INCLUDE_STANDALONE_SYM_TBL \
	INCLUDE_STDIO \
	INCLUDE_SYM_SHELL_CMD \
	INCLUDE_SYM_TBL \
	INCLUDE_SYM_TBL_INIT \
	INCLUDE_SYM_TBL_SHOW \
	INCLUDE_SYSCLK_INIT \
	INCLUDE_SYSDBG_FLAG \
	INCLUDE_SYSHW_INIT \
	INCLUDE_SYSHW_INIT2 \
	INCLUDE_SYS_START \
	INCLUDE_TASK_CREATE_DELETE \
	INCLUDE_TASK_CREATE_HOOKS \
	INCLUDE_TASK_HOOKS \
	INCLUDE_TASK_HOOKS_SHOW \
	INCLUDE_TASK_INFO \
	INCLUDE_TASK_LIST \
	INCLUDE_TASK_RESTART \
	INCLUDE_TASK_SHELL_CMD \
	INCLUDE_TASK_SHOW \
	INCLUDE_TASK_SWAP_HOOKS \
	INCLUDE_TASK_SWITCH_HOOKS \
	INCLUDE_TASK_UTIL \
	INCLUDE_TASK_VARS \
	INCLUDE_TFFS \
	INCLUDE_TFFS_MOUNT \
	INCLUDE_TFFS_SHOW \
	INCLUDE_TIMER_SYS \
	INCLUDE_TIMER_SYS_DELAY \
	INCLUDE_TIMESTAMP \
	INCLUDE_TIMEX \
	INCLUDE_TIP \
	INCLUDE_TIP_CMD \
	INCLUDE_TL_FTL \
	INCLUDE_TTY_DEV \
	INCLUDE_TYLIB \
	INCLUDE_UNLOADER \
	INCLUDE_UNLOADER_SHELL_CMD \
	INCLUDE_USER_APPL \
	INCLUDE_USE_NATIVE_SHELL \
	INCLUDE_VFP \
	INCLUDE_VXBUS \
	INCLUDE_VXBUS_ACTIVATE \
	INCLUDE_VXBUS_DEVICE_CONNECT \
	INCLUDE_VXBUS_DEV_INIT \
	INCLUDE_VXBUS_INIT \
	INCLUDE_VXB_LEGACY_INTERRUPTS \
	INCLUDE_VXB_SYS_CLK \
	INCLUDE_VXB_TIMESTAMP \
	INCLUDE_VXDBG \
	INCLUDE_VXDBG_HOOK \
	INCLUDE_VXDBG_MODULE \
	INCLUDE_VXDBG_RUNCTRL \
	INCLUDE_VXEVENTS \
	INCLUDE_VXMEMPROBE_INIT \
	INCLUDE_VXMUX_MBLK \
	INCLUDE_VXMUX_NULLBUFPOOL \
	INCLUDE_VX_TRADITIONAL_SCHEDULER \
	INCLUDE_WATCHDOGS \
	INCLUDE_WATCHDOGS_CREATE_DELETE \
	INCLUDE_WB_RUNTIME_SUPPORT \
	INCLUDE_WDB \
	INCLUDE_WDB_BANNER \
	INCLUDE_WDB_BP \
	INCLUDE_WDB_BP_SYNC \
	INCLUDE_WDB_COMM_END \
	INCLUDE_WDB_CTXT \
	INCLUDE_WDB_DIRECT_CALL \
	INCLUDE_WDB_EVENTPOINTS \
	INCLUDE_WDB_EVENTS \
	INCLUDE_WDB_EXC_NOTIFY \
	INCLUDE_WDB_EXIT_NOTIFY \
	INCLUDE_WDB_FUNC_CALL \
	INCLUDE_WDB_GOPHER \
	INCLUDE_WDB_MDL_SYM_SYNC \
	INCLUDE_WDB_MEM \
	INCLUDE_WDB_POST_KERNEL_INIT \
	INCLUDE_WDB_REG \
	INCLUDE_WDB_START_NOTIFY \
	INCLUDE_WDB_SYS \
	INCLUDE_WDB_SYS_COPROC_REG \
	INCLUDE_WDB_SYS_REG \
	INCLUDE_WDB_TASK \
	INCLUDE_WDB_TASK_BP \
	INCLUDE_WDB_TASK_COPROC_REG \
	INCLUDE_WDB_TASK_HOOKS \
	INCLUDE_WDB_TASK_REG \
	INCLUDE_WDB_USER_EVENT \
	INCLUDE_WDB_VIO \
	INCLUDE_WDB_VIO_LIB \
	INCLUDE_XBD \
	INIT_HWMEMPOOL_GLOBAL

MANAGED_LIBS = libspl.a libtipc.a
COMPONENT_LIBS = libspl.a

PROJECT_LINK_SYMDEFS = 


include $(TGT_DIR)/h/make/defs.project


## project-configuration info


## build-configuration info

ifeq ($(BUILD_SPEC),default)
AS               = ccarm
BOOT_EXTRA       = 
CC               = ccarm
CFLAGS_AS_PROJECT = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/gnu_standard -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -M -w
OPTION_LANG_C    = -xc
POST_BUILD_RULE  = cp vxWorks ../r123
RELEASE_CMD      = bootrom.bin
USER_CFLAGS      = <put your custom flags here>
USE_USER_FLAGS   = NO
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
_USER_CFLAGS     = -std=c99
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_rom)
AS               = ccarm
BOOT_EXTRA       = 
CC               = ccarm
CFLAGS_AS_PROJECT = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/gnu_standard -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -M -w
OPTION_LANG_C    = -xc
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
USER_CFLAGS      = <put your custom flags here>
USE_USER_FLAGS   = NO
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romCompress)
AS               = ccarm
BOOT_EXTRA       = 
CC               = ccarm
CFLAGS_AS_PROJECT = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/gnu_standard -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -M -w
OPTION_LANG_C    = -xc
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
USER_CFLAGS      = <put your custom flags here>
USE_USER_FLAGS   = NO
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

ifeq ($(BUILD_SPEC),default_romResident)
AS               = ccarm
BOOT_EXTRA       = 
CC               = ccarm
CFLAGS_AS_PROJECT = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -xassembler-with-cpp -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
CFLAGS_PROJECT   = -g -fno-builtin -t7 -mfpu=vfp -mfloat-abi=softfp -ansi -fno-zero-initialized-in-bss -Wall -I$(TGT_DIR)/config/all -I$(TGT_DIR)/h -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain -I. -I$(TGT_DIR)/h/wrn/coreip -I$(TGT_DIR)/src/config -I$(TGT_DIR)/config/comps/src -I$(TGT_DIR)/config/comps/src/dosfs2 -I$(TGT_DIR)/src/drv -I$(TGT_DIR)/src/hwif/h -DCPU=_VX_ARMARCH7 -DTOOL_FAMILY=gnu -DTOOL=gnu -D_WRS_KERNEL -DARMEL -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET -D_VSB_CONFIG_FILE=\"$(VSB_CONFIG_FILE)\" -I$(VSB_INCLUDE_DIR)
EXTRA_DEFINE     = -DCPU_CORTEXA8 -DARMMMU=ARMMMU_CORTEXA8 -DARMCACHE=ARMCACHE_CORTEXA15 -DARM_USE_VFP -DIP_PORT_VXWORKS=69 -DINET
EXTRA_INCLUDE    = -I$(WIND_HOME)/components/windml-5.4/src/include/vxworks-6.9 -I$(WIND_HOME)/components/windml-5.4/h -I$(WIND_HOME)/components/webservices-1.8/h -I$(WIND_HOME)/components/webcli-4.9/target/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/hostfs/h -I$(WIND_HOME)/components/tcf_agent-1.4/agent/src/tcflib -I$(WIND_HOME)/components/stacktrace-1.0/include -I$(WIND_HOME)/components/opc-3.2/h -I$(WIND_HOME)/components/dcom-2.3/h -I$(WIND_HOME)/components/cafe-0.1/hpc/include -I$(WIND_HOME)/components/cafe-0.1/cafe/include -I$(WIND_HOME)/components/cafe-0.1/vxworks/include -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/src -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/src -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/src -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/src -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/src -I$(WIND_HOME)/components/windml-5.4/osconfig/vxworks/h -I$(WIND_HOME)/components/tcf_agent-1.4/osconfig/vxworks/h -I$(WIND_HOME)/components/stacktrace-1.0/osconfig/vxworks/h -I$(WIND_HOME)/components/ip_net2-6.9/osconfig/vxworks/h -I$(WIND_HOME)/components/cafe-0.1/osconfig/vxworks/h -I$(TGT_DIR)/src/hwif -I$(TGT_DIR)/src/hwif/h @./ipcom_ipdomain
EXTRA_MODULES    = $(SUB_TARGETS)
LD_LINK_PATH     = -L$(VSB_DIR)/arm/ARMARCH7/gnu_standard -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(VSB_DIR)/arm/ARMARCH7/gnu -L$(VSB_DIR)/arm/ARMARCH7/common -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WS_ROOT_DIR)/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/gnu -L$(WIND_HOME)/components/obj/vxworks-6.9/krnl/lib/arm/ARMARCH7/common
LIBS             = $(VX_OS_LIBS)
OPTION_DEPEND    = -M -w
OPTION_LANG_C    = -xc
RELEASE_CMD      = bootrom.bin
ROM_SIZE         = 00200000 # number of bytes of ROM space
ROM_TEXT_ADRS    = 0fc00000 # ROM entry address
USER_CFLAGS      = <put your custom flags here>
USE_USER_FLAGS   = NO
VFPVARIANT       = VFPv3
VMA_START        = 0x$(ROM_TEXT_ADRS)
HEX_FLAGS        = 
POST_BUILD_RULE  = 
POST_HEX_BUILD_RULE = 
endif

# override make definitions only below this line


# override make definitions only above this line

include $(TGT_DIR)/h/make/rules.project


## build-configuration info

ifeq ($(BUILD_SPEC),default)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c
endif

ifeq ($(BUILD_SPEC),default_rom)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c
endif

ifeq ($(BUILD_SPEC),default_romCompress)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c
endif

ifeq ($(BUILD_SPEC),default_romResident)

usrAppInit.o:  $(PRJ_DIR)/usrAppInit.c 
	$(RM) usrAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrAppInit.c

usrRtpAppInit.o:  $(PRJ_DIR)/usrRtpAppInit.c 
	$(RM) usrRtpAppInit.o
	$(CC) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) -c $(PRJ_DIR)/usrRtpAppInit.c
endif


## user defined rules

vxWorks.res_rom.bin: vxWorks.res_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.res_rom $@

vxWorks_rom.bin: vxWorks_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks_rom $@

bootrom.bin: bootrom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom $@

bootrom_uncmp.bin: bootrom_uncmp
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom_uncmp $@

linkSyms.o : $(PRJ_DIR)/linkSyms.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/linkSyms.c -o $@

bootrom_res.bin: bootrom_res
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary bootrom_res $@

sysLib.o : $(BSP_DIR)/sysLib.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(BSP_DIR)/sysLib.c -o $@

sysALib.o : $(BSP_DIR)/sysALib.s
	$(AS) $(OPTION_OBJECT_ONLY) $(CFLAGS_AS) $(CFLAGS_AS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(BSP_DIR)/sysALib.s -o $@

vxWorks.st_rom.bin: vxWorks.st_rom
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.st_rom $@

vxWorks.res_rom_nosym.bin: vxWorks.res_rom_nosym
	- @ $(RM) $@
	$(EXTRACT_BIN) -O binary vxWorks.res_rom_nosym $@

prjConfig.o : $(PRJ_DIR)/prjConfig.c
	$(CC) $(OPTION_OBJECT_ONLY) $(CFLAGS) $(CFLAGS_OPTIONS_ALL) $(PROJECT_BSP_FLAGS_EXTRA) $(PRJ_DIR)/prjConfig.c -o $@


src_build :

src_depend :

$(PRJ_FULL_PATH)/compObjs.lst : $(PRJ_MAKEFILE)
	@ $(RM) $@
	@ touch $@

src_clean :
	@ $(RM) compObjs.lst
