/****************************************************************************/
/**
*
* @file fmsh_ps_parameters.h
*
* This file is automatically generated

* This file contains the address definitions for the hard peripherals
* attached to the ARM Cortex A7 core.
*
*****************************************************************************/
#if 0
#ifndef _FMSH_PS_PARAMETERS_H_
#define _FMSH_PS_PARAMETERS_H_

#include "ps_init.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************* Constant Definitions *********************/
/*
 * This block contains constant declarations for the peripherals
 * within the hardblock. These have been put for bacwards compatibilty
 */
#define  PSS_IDCODE_DEVICE   PSS_IDCODE_DEVICE_7045

#define FPS_DDR3MEM_BASEADDR         (0x00100000)
#define FPS_GIC_BASEADDR             (0xF8900000)

#define FPS_AHB2APB0_BASEADDR        (0xE0000000)
#define FPS_AHB2APB1_BASEADDR        (0xE0020000)
#define FPS_CSU_BASEADDR             (0xE0040000)
#define FPS_SMC_CTL_BASEADDR         (0xE0041000)
#define FPS_SMC_NORSRAM0_BASEADDR    (0xE2000000)
#define FPS_SMC_NORSRAM1_BASEADDR    (0xE4000000)
#define FPS_QSPI0_D_BASEADDR         (0xE8000000)
#define FPS_QSPI1_D_BASEADDR         (0xE9000000)
#define FPS_NFC_S_BASEADDR           (0xE0042000)
#define FPS_SDMMC0_BASEADDR          (0xE0043000)
#define FPS_SDMMC1_BASEADDR          (0xE0044000)
#define FPS_USB0_BASEADDR            (0xE0045000)
#define FPS_USB1_BASEADDR            (0xE0046000)
#define FPS_GMAC0_BASEADDR           (0xE0047000)
#define FPS_GMAC1_BASEADDR           (0xE0049000)
#define FPS_DMA_BASEADDR             (0xE004B000)
#define FPS_AHB_SRAM_BASEADDR        (0xE1FE0000)

#define FPS_QSPI0_BASEADDR           (0xE0000000)
#define FPS_SPI0_BASEADDR            (0xE0001000)
#define FPS_I2C0_BASEADDR            (0xE0002000)
#define FPS_GPIO_BASEADDR            (0xE0003000)
#define FPS_UART0_BASEADDR           (0xE0004000)
#define FPS_CAN0_BASEADDR            (0xE0005000)
#define FPS_CAN1_BASEADDR            (0xE0006000)
#define FPS_TIMER0_BASEADDR          (0xE0007000)
#define FPS_GTC_BASEADDR             (0xE0008000)
#define FPS_PRCG_BASEADDR            (0xE0009000)

#define FPS_QSPI1_BASEADDR           (0xE0020000)
#define FPS_SPI1_BASEADDR            (0xE0021000)
#define FPS_I2C1_BASEADDR            (0xE0022000)
#define FPS_UART1_BASEADDR           (0xE0023000)
#define FPS_TIMER1_BASEADDR          (0xE0024000)
#define FPS_WDT_BASEADDR             (0xE0025000)
#define FPS_SLCR_BASEADDR            (0xE0026000)
#define FPS_DDR3_CTL_BASEADDR        (0xE0027000)

/******************************************************************/

/* Definitions for driver DMAPS */
#define FPAR_DMAPS_NUM_INSTANCES 1

/* Definitions for peripheral DMA */
#define FPAR_DMAPS_DEVICE_ID 0
#define FPAR_DMAPS_BASEADDR 0xE004B000

/******************************************************************/

/* Definitions for driver SDPS */
#define FPAR_SDPS_NUM_INSTANCES     2

/* Definitions for peripheral PS_SD_0 */
#define FPAR_SDPS_0_DEVICE_ID         0
#define FPAR_SDPS_0_BASEADDR          0xE0043000
#define FPAR_SDPS_0_HIGHADDR          0xE0043FFF
#define FPAR_SDPS_0_SDIO_CLK_FREQ_HZ  100000000
#define FPAR_SDPS_0_HAS_CD            1
#define FPAR_SDPS_0_HAS_WP            1

/* Definitions for peripheral PS_SD_1 */
#define FPAR_SDPS_1_DEVICE_ID         1
#define FPAR_SDPS_1_BASEADDR          0xE0044000
#define FPAR_SDPS_1_HIGHADDR          0xE0044FFF
#define FPAR_SDPS_1_SDIO_CLK_FREQ_HZ  100000000
#define FPAR_SDPS_1_HAS_CD            1
#define FPAR_SDPS_1_HAS_WP            1



/******************************************************************/

/* FMSH FAT File System Library (FmshFFs) User Settings */
#define FILE_SYSTEM_INTERFACE_SD

/* Canonical definitions for peripheral SDMMC */
#define FPAR_SDMMCPS_HAS_CD 1
#define FPAR_SDMMCPS_HAS_WP 1
#define FPAR_SDMMCPS_CLOCK_HZ    SDIO_FREQ



	/* Definitions for driver CANPS */
#define FPAR_CANPS_NUM_INSTANCES 2
	
	/* Definitions for peripheral PS_CAN_0 */
#define FPAR_CANPS_0_DEVICE_ID 0
#define FPAR_CANPS_0_BASEADDR FPS_CAN0_BASEADDR
#define FPAR_CANPS_0_CAN_CLK_FREQ_HZ CAN_FREQ
	
	/* Definitions for peripheral PS_CAN_1 */
#define FPAR_CANPS_1_DEVICE_ID 1
#define FPAR_CANPS_1_BASEADDR FPS_CAN1_BASEADDR
#define FPAR_CANPS_1_CAN_CLK_FREQ_HZ CAN_FREQ


#ifdef __cplusplus
}
#endif

#endif /* protection macro */
#endif

#ifndef _FMSH_PS_PARAMETERS_H_
#define _FMSH_PS_PARAMETERS_H_

#include "ps_init.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************* Constant Definitions *********************/
/*
 * This block contains constant declarations for the peripherals
 * within the hardblock. These have been put for bacwards compatibilty
 */
#define  PSS_IDCODE_DEVICE   PSS_IDCODE_DEVICE_7045

#define FPS_DDR3MEM_BASEADDR         (0x00100000)
#define FPS_GIC_BASEADDR             (0xF8900000)

#define FPS_AHB2APB0_BASEADDR        (0xE0000000)
#define FPS_AHB2APB1_BASEADDR        (0xE0020000)
#define FPS_CSU_BASEADDR             (0xE0040000)
#define FPS_SMC_CTL_BASEADDR         (0xE0041000)
#define FPS_SMC_NORSRAM0_BASEADDR    (0xE2000000)
#define FPS_SMC_NORSRAM1_BASEADDR    (0xE4000000)
#define FPS_QSPI0_D_BASEADDR         (0xE8000000)
#define FPS_QSPI1_D_BASEADDR         (0xE9000000)
#define FPS_NFC_S_BASEADDR           (0xE0042000)
#define FPS_SDMMC0_BASEADDR          (0xE0043000)
#define FPS_SDMMC1_BASEADDR          (0xE0044000)
#define FPS_USB0_BASEADDR            (0xE0045000)
#define FPS_USB1_BASEADDR            (0xE0046000)
#define FPS_GMAC0_BASEADDR           (0xE0047000)
#define FPS_GMAC1_BASEADDR           (0xE0049000)
#define FPS_DMA_BASEADDR             (0xE004B000)
#define FPS_AHB_SRAM_BASEADDR        (0xE1FE0000)

#define FPS_QSPI0_BASEADDR           (0xE0000000)
#define FPS_SPI0_BASEADDR            (0xE0001000)
#define FPS_I2C0_BASEADDR            (0xE0002000)
#define FPS_GPIO_BASEADDR            (0xE0003000)
#define FPS_UART0_BASEADDR           (0xE0004000)
#define FPS_CAN0_BASEADDR            (0xE0005000)
#define FPS_CAN1_BASEADDR            (0xE0006000)
#define FPS_TIMER0_BASEADDR          (0xE0007000)
#define FPS_GTC_BASEADDR             (0xE0008000)
#define FPS_PRCG_BASEADDR            (0xE0009000)

#define FPS_QSPI1_BASEADDR           (0xE0020000)
#define FPS_SPI1_BASEADDR            (0xE0021000)
#define FPS_I2C1_BASEADDR            (0xE0022000)
#define FPS_UART1_BASEADDR           (0xE0023000)
#define FPS_TIMER1_BASEADDR          (0xE0024000)
#define FPS_WDT_BASEADDR             (0xE0025000)
#define FPS_SLCR_BASEADDR            (0xE0026000)
#define FPS_DDR3_CTL_BASEADDR        (0xE0027000)

/******************************************************************/

/* Definitions for driver DMAPS */
#define FPAR_DMAPS_NUM_INSTANCES 1

/* Definitions for peripheral DMA */
#define FPAR_DMAPS_DEVICE_ID          0
#define FPAR_DMAPS_BASEADDR           FPS_DMA_BASEADDR
/******************************************************************/

/* Definitions for driver GPIOPS */
#define FPAR_GPIOPS_NUM_INSTANCES 4

/* Definitions for peripheral GPIO */
#define FPAR_GPIOPS_0_DEVICE_ID          0
#define FPAR_GPIOPS_0_BASEADDR           FPS_GPIO_BASEADDR

#define FPAR_GPIOPS_1_DEVICE_ID          1
#define FPAR_GPIOPS_1_BASEADDR           (FPS_GPIO_BASEADDR+0x100)

#define FPAR_GPIOPS_2_DEVICE_ID          2
#define FPAR_GPIOPS_2_BASEADDR           (FPS_GPIO_BASEADDR+0x200)

#define FPAR_GPIOPS_3_DEVICE_ID          3
#define FPAR_GPIOPS_3_BASEADDR           (FPS_GPIO_BASEADDR+0x400)

/******************************************************************/

/* Definitions for driver SDPS */
#define FPAR_SDPS_NUM_INSTANCES     2

/* Definitions for peripheral PS_SD_0 */
#define FPAR_SDPS_0_DEVICE_ID         0
#define FPAR_SDPS_0_BASEADDR          FPS_SDMMC0_BASEADDR
#define FPAR_SDPS_0_SDIO_CLK_FREQ_HZ  SDIO_FREQ
#define FPAR_SDPS_0_HAS_CD            0
#define FPAR_SDPS_0_HAS_WP            0

/* Definitions for peripheral PS_SD_1 */
#define FPAR_SDPS_1_DEVICE_ID         1
#define FPAR_SDPS_1_BASEADDR          FPS_SDMMC1_BASEADDR
#define FPAR_SDPS_1_SDIO_CLK_FREQ_HZ  SDIO_FREQ
#define FPAR_SDPS_1_HAS_CD            0
#define FPAR_SDPS_1_HAS_WP            0

/******************************************************************/

/* Definitions for peripheral PS_WDT */
#define FPAR_WDTPS_NUM_INSTANCES      1
#define FPAR_WDTPS_DEVICE_ID          0
#define FPAR_WDTPS_BASEADDR           FPS_WDT_BASEADDR

/******************************************************************/

/* Definitions for driver TTCPS */
#define FPAR_TTCPS_NUM_INSTANCES       2
/* Definitions for peripheral PS_TTC_0 */
#define FPAR_TTCPS_0_DEVICE_ID         0
#define FPAR_TTCPS_0_BASEADDR          FPS_TIMER0_BASEADDR
/* Definitions for peripheral PS_TTC_1 */
#define FPAR_TTCPS_1_DEVICE_ID         1
#define FPAR_TTCPS_1_BASEADDR          FPS_TIMER1_BASEADDR

/******************************************************************/

/* Definitions for peripheral PS_GTC */
#define FPAR_GTCPS_NUM_INSTANCES       1
#define FPAR_GTCPS_DEVICE_ID           0
#define FPAR_GTCPS_BASEADDR            FPS_GTC_BASEADDR

/******************************************************************/

/* Definitions for driver CANPS */
#define FPAR_CANPS_NUM_INSTANCES 2

/* Definitions for peripheral PS_CAN_0 */
#define FPAR_CANPS_0_DEVICE_ID 0
#define FPAR_CANPS_0_BASEADDR FPS_CAN0_BASEADDR
#define FPAR_CANPS_0_CAN_CLK_FREQ_HZ CAN_FREQ

/* Definitions for peripheral PS_CAN_1 */
#define FPAR_CANPS_1_DEVICE_ID 1
#define FPAR_CANPS_1_BASEADDR FPS_CAN1_BASEADDR
#define FPAR_CANPS_1_CAN_CLK_FREQ_HZ CAN_FREQ

/******************************************************************/

/* Definitions for driver I2CPS */
#define FPAR_I2CPS_NUM_INSTANCES 2

/* Definitions for peripheral PS_I2C_0 */
#define FPAR_I2CPS_0_DEVICE_ID 0
#define FPAR_I2CPS_0_BASEADDR FPS_I2C0_BASEADDR
#define FPAR_I2CPS_0_I2C_CLK_FREQ_HZ I2C_FREQ

/* Definitions for peripheral PS_I2C_1 */
#define FPAR_I2CPS_1_DEVICE_ID 1
#define FPAR_I2CPS_1_BASEADDR FPS_I2C1_BASEADDR
#define FPAR_I2CPS_1_I2C_CLK_FREQ_HZ I2C_FREQ
/******************************************************************/

#if 0  
/* Definitions for driver GPMACPS */
#define FPAR_GMACPS_NUM_INSTANCES 2

/* Definitions for peripheral PS_GMAC_0 */
#define FPAR_GMACPS_0_DEVICE_ID     0
#define FPAR_GMACPS_0_BASEADDR      FPS_GMAC0_BASEADDR
#define FPAR_GMACPS_0_SPEED         speed_1000
#define FPAR_GMACPS_0_INTERFACE     gmac_path_rgmii

/* Definitions for peripheral PS_GMAC_1 */
#define FPAR_GMACPS_1_DEVICE_ID      1
#define FPAR_GMACPS_1_BASEADDR       FPS_GMAC1_BASEADDR
#define FPAR_GMACPS_1_SPEED          speed_1000
#define FPAR_GMACPS_1_INTERFACE      gmac_path_rgmii
/******************************************************************/
#endif

/* Definitions for driver UARTPS */
#define FPAR_UARTPS_NUM_INSTANCES 2

/* Definitions for peripheral PS_UART_0 */
#define FPAR_UARTPS_0_DEVICE_ID 0
#define FPAR_UARTPS_0_BASEADDR FPS_UART0_BASEADDR
#define FPAR_UARTPS_0_UART_CLK_FREQ_HZ UART_FREQ
#define FPAP_UARTPS_0_HAS_MODEM 0

/* Definitions for peripheral PS_UART_1 */
#define FPAR_UARTPS_1_DEVICE_ID 1
#define FPAR_UARTPS_1_BASEADDR FPS_UART1_BASEADDR
#define FPAR_UARTPS_1_UART_CLK_FREQ_HZ UART_FREQ
#define FPAP_UARTPS_1_HAS_MODEM 0

/******************************************************************/

/* Definitions for driver DEVCPS */
#define FPAR_DEVCPS_NUM_INSTANCES 1

/* Definitions for peripheral PS_DEVC */
#define FPAR_DEVCPS_DEVICE_ID 0
#define FPAR_DEVCPS_BASEADDR FPS_CSU_BASEADDR

/******************************************************************/

/* FMSH FAT File System Library (FmshFFs) User Settings */
#define FILE_SYSTEM_INTERFACE_SD

#ifdef __cplusplus
}
#endif

#endif /* protection macro */

